# syntax=docker/dockerfile:1

ARG NDN_CXX_VERSION=latest
ARG NFD_VERSION=latest
FROM ghcr.io/named-data/nfd-build:${NFD_VERSION} AS build

FROM ghcr.io/named-data/ndn-cxx-runtime:${NDN_CXX_VERSION}

RUN --mount=type=bind,from=build,source=/deps,target=/deps \
    apt-get install -Uy --no-install-recommends $(cat /deps/nfdc) \
        python3 \
    && rm -rf /var/lib/apt/lists/*

COPY --link --from=build /usr/bin/nfdc /usr/bin/
COPY --link --from=build /usr/bin/nfd-status-http-server /usr/bin/
COPY --link --from=build /usr/share/ndn/ /usr/share/ndn/

VOLUME /run/nfd

EXPOSE 8080/tcp

ENTRYPOINT ["/usr/bin/nfd-status-http-server", "--address", "0.0.0.0"]
